import radar from "./radar";

radar({
  svg_id: "radar",
  width: 1450,
  height: 1000,
  title: "Jamie's Tech Radar — 2021.01",
  quadrants: [
    { name: "Languages" },
    { name: "Infrastructure" },
    { name: "Frameworks" },
    { name: "Data Management" },
  ],
  rings: [
    { name: "ADOPT", color: "#93c47d" },
    { name: "TRIAL", color: "#93d2c2" },
    { name: "ASSESS", color: "#fbdb84" },
    { name: "HOLD", color: "#efafa9" },
  ],
  entries: [
    {
      quadrant: 3,
      ring: 0,
      label: "AWS EMR",
      active: false,
      link: "../data_processing/aws_emr.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Spark",
      active: false,
      link: "../data_processing/spark.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "Airflow",
      active: false,
      link: "../data_processing/airflow.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "AWS Data Pipeline",
      active: false,
      link: "../data_processing/aws_data_pipeline.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "Flink",
      active: false,
      link: "../data_processing/flink.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "Google BigQuery",
      active: false,
      link: "../data_processing/google_bigquery.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "Presto",
      active: false,
      link: "../data_processing/presto.html",
    },
    {
      quadrant: 3,
      ring: 2,
      label: "Hadoop",
      active: false,
      link: "../data_processing/hadoop.html",
    },
    {
      quadrant: 3,
      ring: 2,
      label: "YARN",
      active: false,
      link: "../data_processing/yarn.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "Esper",
      active: false,
      link: "../data_processing/esper.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "AWS S3",
      active: false,
      link: "../datastores/aws_s3.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Cassandra",
      active: false,
      link: "../datastores/cassandra.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Elasticsearch",
      active: false,
      link: "../datastores/elasticsearch.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "etcd",
      active: false,
      link: "../datastores/etcd.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "PostgreSQL",
      active: false,
      link: "../datastores/postgresql.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Redis",
      active: false,
      link: "../datastores/redis.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Solr",
      active: false,
      link: "../datastores/solr.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "AWS DynamoDB",
      active: false,
      link: "../datastores/aws_dynamodb.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "HDFS",
      active: false,
      link: "../datastores/hdfs.html",
    },
    {
      quadrant: 3,
      ring: 2,
      label: "Consul",
      active: false,
      link: "../datastores/consul.html",
    },
    {
      quadrant: 3,
      ring: 2,
      label: "Google Bigtable",
      active: false,
      link: "../datastores/google_bigtable.html",
    },
    {
      quadrant: 3,
      ring: 2,
      label: "RocksDB",
      active: false,
      link: "../datastores/rocksdb.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "Aerospike",
      active: false,
      link: "../datastores/aerospike.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "CouchBase",
      active: false,
      link: "../datastores/couchbase.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "HBase",
      active: false,
      link: "../datastores/hbase.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "Memcached",
      active: false,
      link: "../datastores/memcached.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "MongoDB",
      active: false,
      link: "../datastores/mongodb.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "MySQL",
      active: false,
      link: "../datastores/mysql.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "Oracle DB",
      active: false,
      link: "../datastores/oracle_db.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "ZooKeeper",
      active: false,
      link: "../datastores/zookeeper.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "Akka (Scala)",
      active: false,
      link: "../frameworks/akka_scala.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "Node.js",
      active: false,
      link: "../frameworks/nodejs.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "Play (Scala)",
      active: false,
      link: "../frameworks/play_scala.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "ReactJS",
      active: false,
      link: "../frameworks/reactjs.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "RxJava (Android)",
      active: false,
      link: "../frameworks/rxjava_android.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "scikit-learn",
      active: false,
      link: "../frameworks/scikit_learn.html",
    },
    {
      quadrant: 2,
      ring: 0,
      label: "Spring",
      active: false,
      link: "../frameworks/spring.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "Akka-Http",
      active: false,
      link: "../frameworks/akka_http.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "Angular",
      active: false,
      link: "../frameworks/angular.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "AspectJ",
      active: false,
      link: "../frameworks/aspectj.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "Camel",
      active: false,
      link: "../frameworks/camel.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "Camunda",
      active: false,
      link: "../frameworks/camunda.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "OpenNLP",
      active: false,
      link: "../frameworks/opennlp.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "TensorFlow",
      active: false,
      link: "../frameworks/tensorflow.html",
    },
    {
      quadrant: 2,
      ring: 1,
      label: "Thymeleaf",
      active: false,
      link: "../frameworks/thymeleaf.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "Aurelia",
      active: false,
      link: "../frameworks/aurelia.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "Ember.js",
      active: false,
      link: "../frameworks/emberjs.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "gRPC",
      active: false,
      link: "../frameworks/grpc.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "Http4s",
      active: false,
      link: "../frameworks/http4s.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "jOOQ",
      active: false,
      link: "../frameworks/jooq.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "Redux",
      active: false,
      link: "../frameworks/redux.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "Vert.x",
      active: false,
      link: "../frameworks/vertx.html",
    },
    {
      quadrant: 2,
      ring: 2,
      label: "Vue.js",
      active: false,
      link: "../frameworks/vuejs.html",
    },
    {
      quadrant: 2,
      ring: 3,
      label: "Activiti",
      active: false,
      link: "../frameworks/activiti.html",
    },
    {
      quadrant: 2,
      ring: 3,
      label: "AngularJS 1.x",
      active: false,
      link: "../frameworks/angularjs_1x.html",
    },
    {
      quadrant: 2,
      ring: 3,
      label: "BackboneJS",
      active: false,
      link: "../frameworks/backbonejs.html",
    },
    {
      quadrant: 2,
      ring: 3,
      label: "Drools",
      active: false,
      link: "../frameworks/drools.html",
    },
    {
      quadrant: 2,
      ring: 3,
      label: "Spray",
      active: false,
      link: "../frameworks/spray.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "Docker",
      active: false,
      link: "../infrastructure/docker.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "Hystrix",
      active: false,
      link: "../infrastructure/hystrix.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "Kubernetes",
      active: false,
      link: "../infrastructure/kubernetes.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "Nginx",
      active: false,
      link: "../infrastructure/nginx.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "OpenTracing",
      active: false,
      link: "../infrastructure/opentracing.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "Tomcat",
      active: false,
      link: "../infrastructure/tomcat.html",
    },
    {
      quadrant: 1,
      ring: 0,
      label: "ZMON",
      active: false,
      link: "../infrastructure/zmon.html",
    },
    {
      quadrant: 1,
      ring: 1,
      label: "Failsafe",
      active: false,
      link: "../infrastructure/failsafe.html",
    },
    {
      quadrant: 1,
      ring: 1,
      label: "Undertow",
      active: false,
      link: "../infrastructure/undertow.html",
    },
    {
      quadrant: 1,
      ring: 2,
      label: "AWS Lambda",
      active: false,
      link: "../infrastructure/aws_lambda.html",
    },
    {
      quadrant: 1,
      ring: 3,
      label: "STUPS",
      active: false,
      link: "../infrastructure/stups.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "Go",
      active: true,
      link: "go.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "Java",
      active: true,
      link: "java.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "JavaScript",
      active: true,
      link: "javascript.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "OpenAPI (Swagger)",
      active: true,
      link: "openapi_swagger.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "Python",
      active: true,
      link: "python.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "Scala",
      active: true,
      link: "scala.html",
    },
    {
      quadrant: 0,
      ring: 0,
      label: "Swift",
      active: true,
      link: "swift.html",
    },
    {
      quadrant: 0,
      ring: 3,
      label: "Clojure",
      active: true,
      link: "clojure.html",
    },
    {
      quadrant: 0,
      ring: 1,
      label: "GraphQL",
      active: true,
      link: "graphql.html",
    },
    {
      quadrant: 0,
      ring: 3,
      label: "Haskell",
      active: true,
      link: "haskell.html",
    },
    {
      quadrant: 0,
      ring: 1,
      label: "Kotlin",
      active: true,
      link: "kotlin.html",
    },
    {
      quadrant: 0,
      ring: 1,
      label: "TypeScript",
      active: true,
      link: "typescript.html",
    },
    {
      quadrant: 0,
      ring: 2,
      label: "R",
      active: true,
      link: "r.html",
    },
    {
      quadrant: 0,
      ring: 3,
      label: "Rust",
      active: true,
      link: "rust.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "AWS SNS",
      active: false,
      link: "../queues/aws_sns.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "AWS SQS",
      active: false,
      link: "../queues/aws_sqs.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Kafka",
      active: false,
      link: "../queues/kafka.html",
    },
    {
      quadrant: 3,
      ring: 0,
      label: "Nakadi",
      active: false,
      link: "../queues/nakadi.html",
    },
    {
      quadrant: 3,
      ring: 1,
      label: "RabbitMQ",
      active: false,
      link: "../queues/rabbitmq.html",
    },
    {
      quadrant: 3,
      ring: 2,
      label: "AWS Kinesis",
      active: false,
      link: "../queues/aws_kinesis.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "ActiveMQ",
      active: false,
      link: "../queues/activemq.html",
    },
    {
      quadrant: 3,
      ring: 3,
      label: "HornetQ",
      active: false,
      link: "../queues/hornetq.html",
    },
  ],
});
